Update dynamic_shapes and variables_and_state notebooks.
Python bindings for the variables_and_state notebook are broken, but the exported program still work from the C sample application:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-93e08305c865> in <cell line: 8>()
      6
      7 print(counter.get_value().to_host())
----> 8 counter.set_value(101)
      9 print(counter.get_value().to_host())
     10

1 frames
/usr/local/lib/python3.9/dist-packages/iree/runtime/function.py in __call__(self, *args, **kwargs)
    128       if call_trace:
    129         call_trace.add_vm_list(arg_list, "args")
--> 130       self._invoke(arg_list, ret_list)
    131       if call_trace:
    132         call_trace.add_vm_list(ret_list, "results")

/usr/local/lib/python3.9/dist-packages/iree/runtime/function.py in _invoke(self, arg_list, ret_list)
    152   # Break out invoke so it shows up in profiles.
    153   def _invoke(self, arg_list, ret_list):
--> 154     self._vm_context.invoke(self._vm_function, arg_list, ret_list)
    155
    156   def _parse_abi_dict(self, vm_function: VmFunction):

RuntimeError: Error invoking function: main_checkout/runtime/src/iree/vm/list.c:820: FAILED_PRECONDITION
```