[build system] Correctly link against -lrt in linux (#23723)
Commit c02e48b3ab added `shm_posix.c` which calls `shm_open` and
`shm_unlink`. On older systems (like the manylinux CI container) these
symbols are located in the `rt` library, and one needs to link against
`lrt`.

We make sure to only link `-lrt` when targeting linux.

The original attempt to link against rt used linkopts, but using
bazel_to_cmake reveals that conversion from linkopts in bazel to cmake
is unimplemented.

```
eochoalo@shark-mkm-2:~/code/iree$ ./build_tools/bazel_to_cmake/bazel_to_cmake.py
Using repo root /home/eochoalo/code/iree
Converting directory tree rooted at: /home/eochoalo/code/iree/compiler
0 CMakeLists.txt files were updated, 7 were skipped, and 285 required no change.
Converting directory tree rooted at: /home/eochoalo/code/iree/runtime
  ERROR generating runtime/src/iree/base/internal.
  Missing a rule handler in bazel_to_cmake_converter.py?
  Reason: `NotImplementedError: Unimplemented linkopts: `
0 CMakeLists.txt files were updated, 17 were skipped, and 117 required no change.
ERROR: Encountered unexpected errors converting 1 directories:
  runtime/src/iree/base/internal
```

Using iree_cc_library appears to be the idiomatic way of doing this.

I was able to build `iree_async_platform_io_uring_cts_buffer_tests`
locally after these changes in the same container as CI.

Assisted-by: Claude