[runtime] Fix runtime tracing compile failure on gcc (#19642)
When compiling with gcc I'm getting an error due to the definition of
`std::atomic<uint32_t> next_tracing_thread_i` having a different
language linkage than the declaration:

```
iree/runtime/src/iree/base/tracing/tracy.cc:468:23: error: conflicting declaration of ‘std::atomic<unsigned int> iree_tracing_context_t::next_tracing_thread_id’ with ‘C’ linkage
```

Strangely, clang seems to be fine with this [godbolt gcc vs
clang](https://godbolt.org/z/Yhfcjhchd).

Signed-off-by: Ian Wood <ianwood2024@u.northwestern.edu>