Fix build failure on GCC (#20231)
Use function overload instead of explicit specialization to fix GCC
error:

```
/__w/iree/iree/compiler/src/iree/compiler/Utils/OptionUtils.h:58:13: error: explicit specialization in non-namespace scope 'struct mlir::iree_compiler::opt_initializer<Ty>'
   58 |   template <>
      |          
```

Signed-off-by: Ian Wood <ianwood2024@u.northwestern.edu>