Fix parentheses warning in ireeGPUGetSingleSubgroupLayout (#21558)
Fix for following warning which was introduced recently in
https://github.com/iree-org/iree/pull/21454:
```
iree/compiler/API/Internal/IREEGPUDialectCAPI.cpp: In function ‘ireeGPUMMASingleSubgroupLayout ireeGPUGetSingleSubgroupLayout(MlirAttribute, uint32_t)’:
iree/compiler/src/iree/compiler/API/Internal/IREEGPUDialectCAPI.cpp:357:59: error: suggest parentheses around ‘&&’ within ‘||’ [-Werror=parentheses]
  357 |          ireeAttributeIsAGPUVirtualMMAIntrinsicAttr(attr) &&
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
  358 |              "Expected MMA or VirtualMMA Intrinsic");
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
```

Signed-off-by: Jorn Tuyls <jorn.tuyls@gmail.com>