[CI] Upgrade to GCC 11 to fix stablehlo template instantiation error (#23008)
The GCC CI workflow was failing to build stablehlo due to a C++ template
instantiation issue with GCC 9.

[StablehloAggressiveFolder.cpp](https://github.com/openxla/stablehlo/blob/4a6ea0d65a0ed97f91a04276fcda88fc516ae6de/stablehlo/transforms/optimization/StablehloAggressiveFolder.cpp#L499-L507)
uses modern C++ patterns combining if constexpr with SFINAE-based type
traits:
```
if constexpr (fold_unary::DirectFolderExists<Impl, APInt>::value) {
    return FoldIfImplemented<APInt>(operand);
}
```

GCC 9 incorrectly evaluates these type traits eagerly before the if
constexpr condition is resolved, causing "incomplete type" errors:
```
/__w/iree/iree/third_party/stablehlo/stablehlo/transforms/optimization/StablehloAggressiveFolder.cpp:501:48: error: no matching function for call to 'FoldIfImplemented<llvm::APInt>(llvm::APInt&)'

/__w/iree/iree/third_party/stablehlo/stablehlo/transforms/optimization/StablehloAggressiveFolder.cpp:464:78: error: incomplete type 'fold_unary::DirectFolderExists<Impl, llvm::APInt>' used in nested name specifier
```

Upgrade to GCC 11 resolves this problem.

Before:
https://github.com/iree-org/iree/actions/runs/20654878139/job/59305852621

After:
https://github.com/iree-org/iree/actions/runs/20660113060/job/59320617905?pr=23008

---------

Signed-off-by: Yu-Zhewen <zhewenyu@amd.com>
Signed-off-by: Keshav Vinayak Jha <keshavvinayakjha@gmail.com>