Update onnx package version minimum to 1.16.0. (#17504)
As discovered on
https://github.com/iree-org/iree/pull/17476#discussion_r1617673191, this
is needed to avoid an error running `iree-import-onnx` on certain test
files:

> onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version
10 is higher than the checker's (9).

If we care about supporting older onnx package versions, we could add
some fallback code to `iree-import-onnx`.

We may also want to update the version used in torch-mlir?
https://github.com/llvm/torch-mlir/blob/e0a5adb1db38b0072c44b87570bc530eb3b324ad/setup.py#L264