Fix executable names for web samples.
* Use `_` instead of `-` in names, as they will appear in C++ identifiers (a more general name sanitization might be better than this bandaid)
* Update static library name from 'llvm' to 'llvm_cpu'

```
[2022-08-13T00:19:29Z] In file included from /usr/src/github/iree/experimental/web/sample_static/device_sync.c:9:
[2022-08-13T00:19:29Z] /usr/src/github/iree/build-emscripten/experimental/web/sample_static/mnist_static.h:11:67: error: extra tokens at end of #ifndef directive [-Werror,-Wextra-tokens]
[2022-08-13T00:19:29Z] #ifndef IREE_GENERATED_STATIC_EXECUTABLE_LIBRARY_MNIST_LINKED_LLVM-CPU_
[2022-08-13T00:19:29Z]                                                                   ^
[2022-08-13T00:19:29Z]                                                                   //
[2022-08-13T00:19:29Z] /usr/src/github/iree/build-emscripten/experimental/web/sample_static/mnist_static.h:12:67: error: ISO C99 requires whitespace after the macro name [-Werror,-Wc99-extensions]
[2022-08-13T00:19:29Z] #define IREE_GENERATED_STATIC_EXECUTABLE_LIBRARY_MNIST_LINKED_LLVM-CPU_
[2022-08-13T00:19:29Z]                                                                   ^
[2022-08-13T00:19:29Z] /usr/src/github/iree/build-emscripten/experimental/web/sample_static/mnist_static.h:21:18: error: expected ';' after top level declarator
[2022-08-13T00:19:29Z] mnist_linked_llvm-cpu_library_query(
[2022-08-13T00:19:29Z]                  ^
[2022-08-13T00:19:29Z]                  ;
[2022-08-13T00:19:29Z] /usr/src/github/iree/experimental/web/sample_static/device_sync.c:18:7: error: use of undeclared identifier 'mnist_linked_llvm_library_query'
[2022-08-13T00:19:29Z]       mnist_linked_llvm_library_query,
[2022-08-13T00:19:29Z]       ^                                                           //
```