Revert "Handle symbol name conflicts during executable linking." (#6062)
Reverts google/iree#5978

This broke some benchmark builds ([logs](https://buildkite.com/iree/iree-android-benchmark/builds/2658#c7c611a3-414b-402e-b621-4cebeb4294ac))

```
mobilenet-v2/iree_input.mlir:783:12: error: redefinition of symbol named '__constant_32xf32_0'
```