Use SmallVector instead of std::vector
We can avoid allocation to some extent and this also resolves the
compilation error on Windows:

  error: indirection requires pointer operand