[runtime][hip] Cast IREE_[HOST|DEVICE]_MAX_SIZE to iree_host_size_t type (#19766)
The revision fixes the `-Wformat` errors on platforms that treat
`size_t` as `unsigned long long`. See below error log:

```
error: format specifies type 'size_t' (aka 'unsigned long') but the argument has type 'unsigned long long' [-Werror,-Wformat]
                            IREE_HOST_SIZE_MAX);
```

The error is introduced by https://github.com/iree-org/iree/pull/19667

Signed-off-by: hanhanW <hanhan0912@gmail.com>
Signed-off-by: Liao <dezhliao@amd.com>