Workaround some gcc 13.2.0+ warnings. (#15638)
Fixes https://github.com/openxla/iree/issues/15631 . We recommend using
clang / MSVC instead of gcc (for _many_ reasons), but many Linux
distributions default to using gcc, so it helps to have a
clean/successful build there. Our gcc build bot on CI is running gcc 9,
while 13+ is available.

## `-Wno-overloaded-virtual`

At least gcc 13.2.0 reports more warnings with this than clang, like
these:

```
/usr/local/google/home/lubol/iree/compiler/plugins/input/StableHLO/stablehlo-iree/Conversion/StableHLOToLinalgPointwise.cpp:261:63: required from here
/usr/local/google/home/lubol/iree/third_party/llvm-project/mlir/include/mlir/IR/PatternMatch.h:254:16: error: ‘virtual void mlir::RewritePattern::rewrite(mlir::Operation*, mlir::PatternRewriter&) const’ was hidden [-Werror=overloaded-virtual=]
254 | virtual void rewrite(Operation *op, PatternRewriter &rewriter) const;
| ^~~~~~~
/usr/local/google/home/lubol/iree/third_party/llvm-project/mlir/include/mlir/Transforms/DialectConversion.h:544:16: note: by ‘mlir::OpConversionPatternmlir::stablehlo::XorOp::rewrite’
544 | virtual void rewrite(SourceOp op, OpAdaptor adaptor,
| ^~~~~~~
cc1plus: all warnings being treated as errors
[5913/7172] Building CXX object compil...ib/Dialect/Torch/IR/TorchDialect.cpp.o
```

The warnings may be legit, but I can't really figure out how to resolve
them, and other compilers (with the same warning) don't complain.

## `<1>` in types

These produce warnings like this:

```
[build] /usr/include/c++/13/bits/stl_algobase.h:437:30: error: ‘void* __builtin_memmove(void*, const void*, long unsigned int)’ forming offset 24 is out of the bounds [0, 24] of object ‘<anonymous>’ with type ‘llvm::SmallVector<long int, 1>’ [-Werror=array-bounds=]
[build]   437 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);
[build]       |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```