Fix SmallVector conversion error with gcc (#21725)
Fixes the following error I get when compiling with gcc after
https://github.com/iree-org/iree/pull/21719:
```
iree/compiler/src/iree/compiler/Dialect/Stream/Transforms/SpecializeEncodings.cpp: In instantiation of ‘llvm::SmallVector<const T*> mlir::iree_compiler::IREE::Stream::{anonymous}::gatherUsedDialectInterfaces(mlir::ModuleOp) [with T = mlir::iree_compiler::IREE::Stream::AffinityAnalysisDialectInterface]’:
iree/compiler/src/iree/compiler/Dialect/Stream/Transforms/SpecializeEncodings.cpp:524:54:   required from here
iree/compiler/Dialect/Stream/Transforms/SpecializeEncodings.cpp:61:10: error: could not convert ‘results’ from ‘SmallVector<[...],4>’ to ‘SmallVector<[...],6>’
   61 |   return results;
      |          ^~~~~~~
      |          |
      |          SmallVector<[...],4>
ninja: build stopped: subcommand failed.
```

Signed-off-by: Jorn Tuyls <jorn.tuyls@gmail.com>
Signed-off-by: keshavvinayak01 <keshavvinayakjha@gmail.com>