[CPU] Limit vectorization tile sizes for SVE
This prevents large vector sizes. A regression test is included with a
linalg.pooling_nchw_max operation that currently fails to compile with

  error: One or more operations with large vector sizes (8192 bytes) were found:

when SVE is enabled, even though SVE isn't used.

Signed-off-by: Cullen Rhodes <cullen.rhodes@arm.com>