build: symbol renaming
This PR renames all mlir/llvm symbols to something else. That way we will never
have a symbol clash when loading a plugin that links to MLIR/LLVM already,
because they are named differently. We do this with llvm-objcopy and a
generated map file.

This also enables projects to use a black box backend potentially also
depending on another version of MLIR while we can use our backends safely in
the same process.

Signed-off-by: Jelle Schuhmacher <schuehmacher@roofline.ai>