Added missing dependencies for the bazel build (#20719)
This resolves build errors like this:
```
In file included from compiler/src/iree/compiler/Dialect/TensorExt/IR/TensorExtTypes.cpp:7:
In file included from compiler/src/iree/compiler/Dialect/TensorExt/IR/TensorExtTypes.h:10:
compiler/src/iree/compiler/Dialect/TensorExt/IR/TensorExtDialect.h:12:10: error: module //compiler/src/iree/compiler/Dialect/TensorExt/IR:IR does not depend on a module exporting 'mlir/Support/TypeID.h'
   12 | #include "mlir/Support/TypeID.h"
      |          ^
In file included from compiler/src/iree/compiler/Dialect/TensorExt/IR/TensorExtTypes.cpp:7:
compiler/src/iree/compiler/Dialect/TensorExt/IR/TensorExtTypes.h:20:10: error: module //compiler/src/iree/compiler/Dialect/TensorExt/IR:IR does not depend on a module exporting 'mlir/Support/LLVM.h'
   20 | #include "mlir/Support/LLVM.h"
```

Signed-off-by: Vladimir N. Silyaev <vsilyaev@gmail.com>
Co-authored-by: Vladimir N. Silyaev <vsilyaev@gmail.com>